# Generated by Django 3.0.5 on 2020-12-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTNBackEnd', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='inp_img',
            new_name='Input_Image',
        ),
    ]
