# Generated by Django 3.0.5 on 2020-12-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTNBackEnd', '0003_auto_20201210_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='NULL', max_length=50),
            preserve_default=False,
        ),
    ]
