# Generated by Django 3.0.5 on 2020-12-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTNBackEnd', '0004_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
